query ThemeQuery($endDate: CmsDateTime!) {
    cms {
        events(
      limit: 1,
      order: startsAt_ASC,
      where: {
        program: { webname: "codeday" }
        endsAt_gte: $endDate,
      }
    ) {
        items {
            theme
        }
    }
    } 
}